Homework 1
MikeRos/2020-1-Atom-QA-Python-M-Roshchin pull request #1
Opened 2020-03-02 20:22 UTC by MikeRos

# Домашнее задание № 1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
* Подготовка рабочего окружения для разработки автоматических тестов
* По 5 тестов для pytest на каждую из структур данных в Python:
  1. List
  2. Set
  3. Dictionary
  4. String
  5. Int
* Проверка стиля кода линтером pylint

2020-03-04 20:31 UTC, sniiick requested changes
По тестам в целом вопросов нет, но isinstance в каждом тесте несколько перебор.
Дополнительно к тому что в комментах:
1. нужно переместить всю 1 домашку в отдельную папку
2. нужно тесты для разных структур перенести в свои отдельные файлы

2020-03-04 20:31 UTC, snicks92 commented on tests/test_hw_1.py
> +from fixtures.some_fixtures import random_int, random_sign
Эту строчку лучше поместить в conftest.py

2020-03-04 20:31 UTC, snicks92 commented on tests/test_hw_1.py
> +        assert isinstance(a, list) and isinstance(a, list) and a + b == [0, 1]
Дважды `isinstance(a, list)`.

Отдельно вопрос, зачем в каждом тесте делать isinstance того что тестируется? Если хочется проверить именно этот метод, то лучше сделать отдельный тест чисто на это. Если хочется убедиться что на вход верные данные, то в данных тестах это не нужно. 

То есть если тест называется `test_list_concatenate` то логично что на вход не должны податься не списки.

Это надо везде поправить

2020-03-05 16:08 UTC, MikeRos commented on tests/test_hw_1.py
> +        assert isinstance(a, list) and isinstance(a, list) and a + b == [0, 1]
> убедиться что на вход поданы верные данные
Именно, и что типы случайно не изменились по ходу теста.
Поправил это и остальные замечания.

2020-03-06 16:01 UTC, MikeRos commented
Замечания исправлены
- переместить всю 1 домашку в отдельную папку
- тесты для разных структур перенести в свои отдельные файлы
- строчку лучше поместить в conftest.py
- поправить isinstance

2020-03-06 17:28 UTC, snicks92 commented on tests/test_hw_1.py
> +        assert isinstance(a, list) and isinstance(a, list) and a + b == [0, 1]
> > убедиться что на вход поданы верные данные
> 
> Именно, и что типы случайно не изменились по ходу теста.
> Поправил это и остальные замечания.

Идея хорошая но тестировать то что сам подаешь на вход - довольно странная идея.

2020-03-06 17:32 UTC, sniiick approved these changes

2020-03-06 17:32 UTC, merged